---
# see references: 
# https://docs.ansible.com/ansible/2.9_ja/plugins/inventory/vultr.html
plugin: vultr
keyed_groups:
  - prefix: kind
    key: tag | lower
  - separator: ""
    key: os

groups:
  k8s_masters: "('master' in tag) and ('k8s' in tag)"
  k8s_workers: "('worker' in tag) and ('k8s' in tag)"
