---

- block:

  - name: Place the encryption config
    include_tasks: itr_place.yml
    with_inventory_hostnames:
      - k8s_masters
    loop_control:
      loop_var: host

  become: yes
  tags:
    - construct
    - kubernetes
    - encryption_config
    - place
