---

- block:

  - name: Register authorized_key
    authorized_key:
      user: "{{ var_ansible_user_name }}"
      key: "{{ hostvars[executer_host].executer_key.public_key }}"
      state: present

  become: yes
  tags:
    - construct
    - authkey
