---

- block:

  - name: Create ansible group
    group:
      name: "{{ var_ansible_user_group }}"
      state: present

  - name: Create ansible user
    user:
      name: "{{ var_ansible_user_name }}"
      password: "{{ var_ansible_user_pwd }}"
      groups: "{{ var_ansible_user_group }},wheel"
      shell: /bin/bash
  
  become: yes
  tags:
    - construct
    - ansible_user
