---

- block:

  - name: Setup ansible ssh connections
    include_tasks: itr_gen_key.yml
    with_items: "{{ var_cluster_pki_config.keyinfos }}"
    loop_control:
      loop_var: keyinfo

  become: yes
  tags:
    - construct
    - pki
    - genkeys
