---

- block:

  - name: Create ca.key
    community.crypto.openssl_privatekey:
      path: /ansible/.keys/ca.key
      size: 2048
      type: RSA
  
  - name: Create certificate signing request (CSR) for CA certificate
    community.crypto.openssl_csr_pipe:
      privatekey_path: /ansible/.keys/ca.key
      common_name: KUBERNETES-CA
      use_common_name_for_san: false
      basic_constraints:
        - 'CA:TRUE'
      basic_constraints_critical: true
      key_usage:
        - keyCertSign
      key_usage_critical: true
    register: ca_csr

  - name: Create self-signed CA certificate from CSR
    community.crypto.x509_certificate:
      path: /ansible/.keys/ca.crt
      csr_content: "{{ ca_csr.csr }}"
      privatekey_path: /ansible/.keys/ca.key
      provider: selfsigned

  become: yes
  tags:
    - construct
    - pki
    - cakey
