---

- hosts: executers
  gather_facts: true
  roles:
    - k8s_manager

- hosts: all,!executers
  gather_facts: true
  become: true
  vars:
    executer_host: "executer"
  roles:
    - ansible_user
    - opsystem

- hosts: executers
  gather_facts: true
  roles:
    - { role: pki/crt_key_gen }
    - role: pki/distribute_keys
      vars:
        distribute_to: "{{ groups['k8s_masters'] }}"
    - { role: kubernetes/configure/certificate_config }

- hosts: all,!executers
  gather_facts: true
  become: true
  vars:
    executer_host: "executer"
  roles:
    - cri_containerd
    - kubetools
